### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by s9eenk** [pawan-delhi/payumoney-node#1]
Hi pawan. Gone through your utility , applied the same but not working the "makePayment logic" steps in else condition and provide output "undefined". Please find the screen shot attached. Any help in this regard is appreciated. 
![ee](https://user-images.githubusercontent.com/23517231/35383199-9a03585a-01e7-11e8-9b86-968099b1ccef.png)

**Comment by abmnukmr** [comment]
var paymentData = {
productinfo: "JFHJH",
txnid: "HHJFJ",
amount: "1KGKJG",
email: "XXXXXX@gmail.com",
phone: "*********5",
lastname: "Abhimanyu ",
firstname: "Kumar",
surl: "http://localhost:3000/payu/success",
furl: "http://localhost:3000/payu/fail"
};

Put any value in evey key input
It would help you. :)

**Comment by pawan-delhi** [comment]
Hi,
Sorry for the delayed response, I've updated PayUMoney-node package. Now Test Mode is working perfectly. Use PayUMoney-node version 2.0.0

Thanks
