### ISSUE TITLE
NOT WORKING IN TEST MODE

### ISSUE THREAD

**Issue by reshma-r-p** [pawan-delhi/payumoney-node#2]
I am trying to integrate payumoney in testmode. But its not working. I got "undefined" instead of returning url.

**Comment by abmnukmr** [comment]
txnid: "3245645",
             put some value in txnid

**Comment by pawan-delhi** [comment]
Hi,
Sorry for the delayed response, I've updated PayUMoney-node package. Now Test Mode is working perfectly. Use PayUMoney-node version 2.0.0

Thanks
